function ErrorPage() {
    return (
        <div>
            <h1 className="App-header">Error 404 Page Not Found</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sed ante et arcu finibus porta. Sed diam dui, blandit id euismod sed, consectetur vel mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras dui neque, egestas eu massa vitae, facilisis maximus neque. Suspendisse feugiat nibh sem, vitae rhoncus ante iaculis tempor. Nam consequat aliquam sapien, id congue libero mollis vitae. Sed at sapien a leo lobortis elementum.

Cras mattis nisl in lacus maximus, nec maximus arcu sodales. Quisque neque lacus, blandit a volutpat sit amet, tincidunt vel mi. Quisque sodales sem vel feugiat tincidunt. Vestibulum a tincidunt arcu. Duis lacus arcu, pulvinar non odio a, lobortis laoreet dolor. Nullam sagittis ante a dolor luctus imperdiet. Integer vitae libero sem. Sed malesuada facilisis efficitur. Vivamus non blandit est, vel aliquam diam.

Curabitur fermentum accumsan lorem, a sagittis velit tristique quis. Morbi interdum mauris sem, non suscipit tellus venenatis in. Ut nec sem ut libero suscipit tincidunt sed non risus. Vivamus sapien turpis, porta id convallis non, maximus a libero. Vestibulum ultricies a massa eu imperdiet. Donec elit elit, maximus eget neque in, ultrices pellentesque ipsum. Cras pellentesque libero ut elit eleifend, eu rhoncus mauris gravida. Nullam id tellus tempus, scelerisque justo non, facilisis nibh. Nulla sapien nulla, rhoncus ac imperdiet sit amet, suscipit porttitor leo. Nam sed molestie ligula. Nunc bibendum in nisi eu maximus. Vivamus vehicula sem a odio tempor egestas. Sed justo lorem, maximus a sapien nec, aliquam pretium purus. Proin tincidunt massa turpis. Donec velit odio, malesuada sed felis sed, sodales placerat risus. Sed quis viverra ligula.

Duis eu leo tincidunt, imperdiet felis iaculis, dapibus tortor. Vivamus sodales, velit ac ornare tincidunt, est neque consequat nisi, quis gravida libero nunc in purus. Integer pulvinar id tortor vitae finibus. Praesent porttitor felis vitae pretium ullamcorper. Vestibulum hendrerit leo ut fermentum suscipit. Curabitur risus odio, luctus vel mi in, aliquet laoreet leo. Fusce ac libero sed turpis fringilla mollis. In egestas arcu tempor lacus finibus, at efficitur purus vehicula. Fusce commodo in lacus tempus ultricies. Aliquam hendrerit mauris fringilla neque posuere, feugiat eleifend sem tempus. Nulla eget felis non ipsum vestibulum dapibus quis at neque.

Integer tellus magna, hendrerit imperdiet nibh ac, rutrum pretium velit. Ut vel nunc id massa facilisis ullamcorper sit amet in magna. Ut quam mauris, vestibulum eget suscipit et, venenatis a ex. Cras scelerisque sodales enim eu pulvinar. Aenean maximus mauris lacus, sit amet pulvinar libero rhoncus eu. Aliquam sed lectus nulla. Mauris tempor nec ante eu suscipit. Morbi laoreet eros ac lobortis suscipit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam sem diam, varius nec lectus a, bibendum pellentesque orci. Vestibulum tristique molestie augue, malesuada porta ex vestibulum id. Vestibulum ultrices erat nec interdum luctus. Curabitur mattis ex metus, vel porta turpis viverra et. Suspendisse posuere lacus in sem molestie congue.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sed ante et arcu finibus porta. Sed diam dui, blandit id euismod sed, consectetur vel mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras dui neque, egestas eu massa vitae, facilisis maximus neque. Suspendisse feugiat nibh sem, vitae rhoncus ante iaculis tempor. Nam consequat aliquam sapien, id congue libero mollis vitae. Sed at sapien a leo lobortis elementum.

Cras mattis nisl in lacus maximus, nec maximus arcu sodales. Quisque neque lacus, blandit a volutpat sit amet, tincidunt vel mi. Quisque sodales sem vel feugiat tincidunt. Vestibulum a tincidunt arcu. Duis lacus arcu, pulvinar non odio a, lobortis laoreet dolor. Nullam sagittis ante a dolor luctus imperdiet. Integer vitae libero sem. Sed malesuada facilisis efficitur. Vivamus non blandit est, vel aliquam diam.

Curabitur fermentum accumsan lorem, a sagittis velit tristique quis. Morbi interdum mauris sem, non suscipit tellus venenatis in. Ut nec sem ut libero suscipit tincidunt sed non risus. Vivamus sapien turpis, porta id convallis non, maximus a libero. Vestibulum ultricies a massa eu imperdiet. Donec elit elit, maximus eget neque in, ultrices pellentesque ipsum. Cras pellentesque libero ut elit eleifend, eu rhoncus mauris gravida. Nullam id tellus tempus, scelerisque justo non, facilisis nibh. Nulla sapien nulla, rhoncus ac imperdiet sit amet, suscipit porttitor leo. Nam sed molestie ligula. Nunc bibendum in nisi eu maximus. Vivamus vehicula sem a odio tempor egestas. Sed justo lorem, maximus a sapien nec, aliquam pretium purus. Proin tincidunt massa turpis. Donec velit odio, malesuada sed felis sed, sodales placerat risus. Sed quis viverra ligula.

Duis eu leo tincidunt, imperdiet felis iaculis, dapibus tortor. Vivamus sodales, velit ac ornare tincidunt, est neque consequat nisi, quis gravida libero nunc in purus. Integer pulvinar id tortor vitae finibus. Praesent porttitor felis vitae pretium ullamcorper. Vestibulum hendrerit leo ut fermentum suscipit. Curabitur risus odio, luctus vel mi in, aliquet laoreet leo. Fusce ac libero sed turpis fringilla mollis. In egestas arcu tempor lacus finibus, at efficitur purus vehicula. Fusce commodo in lacus tempus ultricies. Aliquam hendrerit mauris fringilla neque posuere, feugiat eleifend sem tempus. Nulla eget felis non ipsum vestibulum dapibus quis at neque.

Integer tellus magna, hendrerit imperdiet nibh ac, rutrum pretium velit. Ut vel nunc id massa facilisis ullamcorper sit amet in magna. Ut quam mauris, vestibulum eget suscipit et, venenatis a ex. Cras scelerisque sodales enim eu pulvinar. Aenean maximus mauris lacus, sit amet pulvinar libero rhoncus eu. Aliquam sed lectus nulla. Mauris tempor nec ante eu suscipit. Morbi laoreet eros ac lobortis suscipit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam sem diam, varius nec lectus a, bibendum pellentesque orci. Vestibulum tristique molestie augue, malesuada porta ex vestibulum id. Vestibulum ultrices erat nec interdum luctus. Curabitur mattis ex metus, vel porta turpis viverra et. Suspendisse posuere lacus in sem molestie congue.

There is literally nothing here. Other than this wall of text. Obviously this is here, on this page, at this time. You should really go back to a page that actually works. Otherwise, what even is the point of the creators making this entire project? For you to sit around reading a giant block of text on an error page that shouldn't have been seen in the first place? Let's be real now, that wasn't the true purpose of your visit, and if it was then you should really re-evaluate your choices here. Just for you, I'll try to extend this giant wall of text as much as I can so that you, at the very least, feel a little bit accomplished at being able to find this page. But think about it, should you really feel accomplished? You accidentally entered the wrong navigation link, and ended up on a page that you wouldn't have otherwise seen. Maybe you felt like you would discover something cool? Like a special treat that one of the creators of the VPS project left for you, and only you? Well think again my friend. There is and will not be anything here other than this giant wall of text that, for some strange reason, you are still reading in this moment of time. Do you think that, if you get to the very end of this giant wall of text, you'll earn a prize? Well congratulations! You were wrong again. Poor you.</p>
        </div>
    )
}

export default ErrorPage;