function Footer() {
    return (

        <div className="footer">
            <h3>&copy; 2022-16-rtt</h3>

        <div>
            <p className="App-footer">The creators of the VPS project give sincere thanks to: TheCocktailDB and Spoonacular for allowing usage of their API's. </p>

            <h3 className="App-footer">For full disclosure purposes, the creators of the VPS bar are in no way responsible for any possible reactions to any recipe displayed at our bar. The creators of the VPS bar are also in no way responsible for any possible harm, destruction, or oherwise obstructive actions taken by the user, or inflicted upon the user, in the process of using the recipes generated by the bar. By utilizing the tools of this website, the user agrees to these terms. The creators of the VPS project further decline to comment on any potentional questions or concerns regarding certain recipes generated from this project. While the creators are aware that some of the recipes may contain ingredients which are unobtainable or otherwise nonexistent to the user, the creators of the VPS project further suggest that the user simply choose a different recipe to more suit their needs.</h3>

        </div>
    )
}

export default Footer;